[package]
name = "unicol-sandbox"
version = "0.1.0"
edition = "2021"

[dependencies]
bincode = "1.3.3"
once_cell = "1.12.0"
regex = "1.5.6"
serde = { version = "1.0.137", features = ["derive"] }
unicode-canonical-combining-class = { git = "https://github.com/theodore-s-beers/unicode-canonical-combining-class" }
unicode-normalization = "0.1.21"
